---
apiVersion: core.gardener.cloud/v1
kind: ControllerDeployment
metadata:
  name: gardener-extension-shoot-traefik
helm:
  ociRepository:
    ref: registry.local.gardener.cloud:5001/helm-charts/gardener-extension-shoot-traefik:v0.1.0-dev
  values:
    webhook:
      enabled: true
